<?php

namespace ContainerCa02ISw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RSfH1UpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.RSfH1Up' shared service.
     *
     * @return \Symfony\UX\Chartjs\Builder\ChartBuilderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\AdminController::dashboard()": the $chartBuilder argument is type-hinted with the non-existent class or interface: "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface".');
    }
}
