<?php

namespace ContainerRq5gDf8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kd742lcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kd742lc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kd742lc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'question' => ['privates', '.errored..service_locator.kd742lc.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.kd742lc": it references class "App\\Entity\\Question" but no such service exists.'],
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'userVotesAnswersRepository' => ['privates', 'App\\Repository\\UserVotesAnswersRepository', 'getUserVotesAnswersRepositoryService', true],
            'userVotesRepository' => ['privates', 'App\\Repository\\UserVotesRepository', 'getUserVotesRepositoryService', true],
        ], [
            'entityManager' => '?',
            'question' => 'App\\Entity\\Question',
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'userVotesAnswersRepository' => 'App\\Repository\\UserVotesAnswersRepository',
            'userVotesRepository' => 'App\\Repository\\UserVotesRepository',
        ]);
    }
}
