<?php

namespace ContainerT6FlL1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KpfRfZGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kpfRfZG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kpfRfZG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answerRepository' => ['privates', 'App\\Repository\\AnswerRepository', 'getAnswerRepositoryService', true],
        ], [
            'answerRepository' => 'App\\Repository\\AnswerRepository',
        ]);
    }
}
