<?php

namespace ContainerIA6X1Ux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_796TYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._796_TY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._796_TY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chartBuilder' => ['privates', '.errored.RSfH1Up', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::dashboard()": the $chartBuilder argument is type-hinted with the non-existent class or interface: "Symfony\\UX\\Chartjs\\Builder\\ChartBuilderInterface".'],
        ], [
            'chartBuilder' => '?',
        ]);
    }
}
