<?php

namespace ContainerVdmflQI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FbxAbe4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FbxAbe4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FbxAbe4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'answerRepository' => ['privates', 'App\\Repository\\AnswerRepository', 'getAnswerRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userVotesAnswersRepository' => ['privates', 'App\\Repository\\UserVotesAnswersRepository', 'getUserVotesAnswersRepositoryService', true],
        ], [
            'answerRepository' => 'App\\Repository\\AnswerRepository',
            'entityManager' => '?',
            'userVotesAnswersRepository' => 'App\\Repository\\UserVotesAnswersRepository',
        ]);
    }
}
