<?php

namespace ContainerTQQoY3X;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_39aNmgaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.39aNmga' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.39aNmga'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formLoginAuthenticator' => ['privates', 'security.authenticator.form_login.main', 'getSecurity_Authenticator_FormLogin_MainService', true],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'formLoginAuthenticator' => '?',
            'userAuthenticator' => '?',
            'userPasswordHasherInterface' => '?',
        ]);
    }
}
