<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNFSBmx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNFSBmx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNFSBmx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNFSBmx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPNFSBmx\App_KernelDevDebugContainer([
    'container.build_hash' => 'PNFSBmx',
    'container.build_id' => '095c48bd',
    'container.build_time' => 1658608841,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNFSBmx');
