<?php

namespace ContainerMKd0uQ9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S6lACgIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s6lACgI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s6lACgI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'qrCodeGenerator' => ['privates', '.errored.zCmTf3_', NULL, 'Cannot determine controller argument for "App\\Controller\\SecurityController::displayGoogleAuthenticatorQrCode()": the $qrCodeGenerator argument is type-hinted with the non-existent class or interface: "App\\Controller\\QrCodeGenerator". Did you forget to add a use statement?'],
        ], [
            'qrCodeGenerator' => '?',
        ]);
    }
}
