<?php

namespace ContainerON5F1ZP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CEee_QBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cEee.qB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cEee.qB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'question' => ['privates', '.errored..service_locator.cEee.qB.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.cEee.qB": it references class "App\\Entity\\Question" but no such service exists.'],
            'repository' => ['privates', 'App\\Repository\\UserVotesRepository', 'getUserVotesRepositoryService', true],
        ], [
            'entityManager' => '?',
            'question' => 'App\\Entity\\Question',
            'repository' => 'App\\Repository\\UserVotesRepository',
        ]);
    }
}
