<?php

namespace ContainerDYkyW9C;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestion3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t_C_3cc.App\Entity\Question' shared service.
     *
     * @return \App\Entity\Question
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.t_C_3cc": it references class "App\\Entity\\Question" but no such service exists.');
    }
}
