<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL4z4Qiz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL4z4Qiz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL4z4Qiz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL4z4Qiz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL4z4Qiz\App_KernelDevDebugContainer([
    'container.build_hash' => 'L4z4Qiz',
    'container.build_id' => '7880bee4',
    'container.build_time' => 1654880499,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL4z4Qiz');
