<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDeQXf6I\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDeQXf6I/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDeQXf6I.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDeQXf6I\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDeQXf6I\App_KernelDevDebugContainer([
    'container.build_hash' => 'DeQXf6I',
    'container.build_id' => '92701b25',
    'container.build_time' => 1654934965,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDeQXf6I');
