<?php

namespace Container30cYOus;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KlOn_QgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.klOn.qg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.klOn.qg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activitiesRepository' => ['privates', 'App\\Repository\\ActivitiesRepository', 'getActivitiesRepositoryService', true],
            'citiesRepository' => ['privates', 'App\\Repository\\CitiesRepository', 'getCitiesRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'activitiesRepository' => 'App\\Repository\\ActivitiesRepository',
            'citiesRepository' => 'App\\Repository\\CitiesRepository',
            'entityManager' => '?',
        ]);
    }
}
