<?php

namespace ContainerUzU8wYF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSkillsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SkillsController' shared autowired service.
     *
     * @return \App\Controller\SkillsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SkillsController.php';

        $container->services['App\\Controller\\SkillsController'] = $instance = new \App\Controller\SkillsController();

        $instance->setContainer(($container->privates['.service_locator..6XfnfV'] ?? $container->load('get_ServiceLocator__6XfnfVService'))->withContext('App\\Controller\\SkillsController', $container));

        return $instance;
    }
}
