<?php

namespace ContainerCULrmo6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QI1tVrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qI1t_Vr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qI1t_Vr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'question' => ['privates', '.errored..service_locator.qI1t_Vr.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.qI1t_Vr": it references class "App\\Entity\\Question" but no such service exists.'],
            'repository' => ['privates', 'App\\Repository\\UserVotesRepository', 'getUserVotesRepositoryService', true],
        ], [
            'question' => 'App\\Entity\\Question',
            'repository' => 'App\\Repository\\UserVotesRepository',
        ]);
    }
}
